# Parameters for the data ingestion stage
# percentage of data to be used for validation
train_val_split_ratio: 0.2
# random seed for reproducibility
random_seed: 42

# Parameters for the model training stage
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01